spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIHNlY3JldCBrZXkgdGhhdCBzaG91bGQgYmUgcmVwbGFjZWQ=}
#  Expiration units - ms
#  ┌──────────────────┬───────────┐
#  │ Desired lifetime │   Value   │
#  ├──────────────────┼───────────┤
#  │ 1 hour           │ 3600000   │
#  ├──────────────────┼───────────┤
#  │ 12 hours         │ 43200000  │
#  ├──────────────────┼───────────┤
#  │ 24 hours         │ 86400000  │
#  ├──────────────────┼───────────┤
#  │ 7 days           │ 604800000 │
#  └──────────────────┴───────────┘
  expiration: 86400000

admin:
  username: ${DEFAULT_ADMIN_USERNAME}
  password: ${DEFAULT_ADMIN_PASS}

analyzer:
  payment-warning-period: 7

minio:
  url: ${MINIO_URL}
  username: ${MINIO_USER}
  password: ${MINIO_PASS}

demo:
  data:
    enable: ${DEMO_DATA_ENABLE:false}
    amount: ${DEMO_DATA_AMOUNT:200}

db:
  container:
    name: ${DB_CONTAINER_NAME:gorilla-postgres}
  backup:
    cron: ${BACKUP_CRON:0 00 12 * * *}
    pg-dump-path: ${BACKUP_PG_DUMP_PATH:pg_dump}